repos:
  - repo: local
    hooks:
      - id: format-markdown-tables
        name: Format Markdown tables
        entry: npx --yes markdown-table-formatter
        language: system
        types: [markdown]
        pass_filenames: true
        stages: [pre-commit]
      - id: markdownlint
        name: Markdownlint
        entry: npx --yes markdownlint --fix
        language: system
        types: [markdown]
        pass_filenames: true
        stages: [pre-commit]

